### ISSUE TITLE
Laravel Socialiteでtwitterログインを実装する

### ISSUE THREAD

**Issue by hanachan1026** [sou-uemura/ikkoku#12]

**Comment by hanachan1026** [comment]
これ、どうなってんねん！！！！！！！！！！！

**Comment by hanachan1026** [comment]
どうなっっっっっっっっとんん！！！！！！！！！

**Comment by hanachan1026** [comment]
couldn't authorize youのエラーは謎ですね。

時間がかかりすぎるようであれば期限を決めて、

- twitterログインを諦める
- emailでログインに路線変更
- 新規登録時にこのアプリはtwitterを利用しますに同意のチェックボックスを出す
- プロフィールにtwitter urlを貼ってもらう
の方向で行きましょうか。

**Comment by sou-uemura** [comment]
かしこまりました。
ありがとうございます。

**Comment by sou-uemura** [comment]
https://teratail.com/questions/200637?modal=q-comp
